name : Test Mocka Library

on:
  push:
    branches-ignore:
      - main
      - release/*

jobs:
  test-mocka-core:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run mocka-core tests
        run: ./gradlew clean :mocka-core:test

  test-mocka-orm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run mocka-orm tests
        run: ./gradlew clean :mocka-orm:test

  test-mocka-odm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run mocka-odm tests
        run: ./gradlew clean :mocka-odm:test